version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sp-app:v1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sp_postgres_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Plexus44ff12
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: sp_postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Plexus44ff12
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
