logging:
  file:
    name: ${logging.file.path}pinocho.log
    path: ./logs/
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  endpoints:
    health:
      include:
        show-details: always
    web:
      exposure:
        include: '*'
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: Plexus44ff12
    url: jdbc:oracle:thin:@localhost:1522/ORCLPDB1
    username: sp_dev
  jpa:
    show-sql: false
  security:
    csrf:
      disable: true
